# Generated by Django 2.1.1 on 2018-09-23 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Album')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
