# Generated by Django 2.1.1 on 2018-09-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='song',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
